// <auto-generated />
using System;
using DealerAutoMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DealerAutoMVC.Migrations
{
    [DbContext(typeof(DealerAutoContext))]
    partial class DealerAutoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DealerAutoMVC.Models.Klient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Klienci");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KrajPochodzenia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marki");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.ModelSamochodu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CzySprzedany")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HorsePower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kolor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarkaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pojemnosc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Przebieg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rok")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MarkaId");

                    b.ToTable("ModeleSamochodow");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.Transakcja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CenaSprzedazy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataTransakcji")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaPlatnosci")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("KlientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModelSamochoduId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KlientId");

                    b.HasIndex("ModelSamochoduId")
                        .IsUnique();

                    b.ToTable("Transakcje");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenApi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.Wyposazenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AppleCarPlay")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzujnikiParkowania")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KameraCofania")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Klimatyzacja")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModelSamochoduId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Nawigacja")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SkorzanaTapicerka")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModelSamochoduId")
                        .IsUnique();

                    b.ToTable("Wyposazenia");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.ModelSamochodu", b =>
                {
                    b.HasOne("DealerAutoMVC.Models.Marka", "Marka")
                        .WithMany("ModeleSamochodow")
                        .HasForeignKey("MarkaId");

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.Transakcja", b =>
                {
                    b.HasOne("DealerAutoMVC.Models.Klient", "Klient")
                        .WithMany("Transakcje")
                        .HasForeignKey("KlientId");

                    b.HasOne("DealerAutoMVC.Models.ModelSamochodu", "ModelSamochodu")
                        .WithOne("Transakcja")
                        .HasForeignKey("DealerAutoMVC.Models.Transakcja", "ModelSamochoduId");

                    b.Navigation("Klient");

                    b.Navigation("ModelSamochodu");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.Wyposazenie", b =>
                {
                    b.HasOne("DealerAutoMVC.Models.ModelSamochodu", "ModelSamochodu")
                        .WithOne("Wyposazenie")
                        .HasForeignKey("DealerAutoMVC.Models.Wyposazenie", "ModelSamochoduId");

                    b.Navigation("ModelSamochodu");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.Klient", b =>
                {
                    b.Navigation("Transakcje");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.Marka", b =>
                {
                    b.Navigation("ModeleSamochodow");
                });

            modelBuilder.Entity("DealerAutoMVC.Models.ModelSamochodu", b =>
                {
                    b.Navigation("Transakcja");

                    b.Navigation("Wyposazenie");
                });
#pragma warning restore 612, 618
        }
    }
}
